[IMP] Invoice structured partner communication
houssine78/addons pull request #128
Opened 2019-02-28 08:45 UTC by nicolasj77

Ajout de la communication structurée sur une facture fournisseur.
Il faudrait vérifier les traduction une fois le module mis en test. C'est important car si les termes ne sont pas traduits cela peut prêter à confusion.

2019-03-04 16:08 UTC, robinkeunen requested changes
LGTM except for a small comment.

2019-03-04 16:08 UTC, robinkeunen commented on account_invoice_structured_communication/models/account_invoice.py
> +    provider_reference = fields.Char(string="Provider reference invoice",
How do you get the reference? Is it a normal field on the forms?

In that case, remove the `store` parameter which is used to store `computed` fields.

2019-03-04 16:12 UTC, robinkeunen commented
And more generally, commit messages should be more explicit about your work. For example, `add files` should be `[ADD] ais__communication: add partner reference field`

2019-03-11 15:05 UTC, remytms approved these changes
LGTM. :)

2019-03-12 09:46 UTC, merged