[IMP] Product report 65 bc
houssine78/addons pull request #130
Opened 2019-03-05 12:07 UTC by nicolasj77

Possibilité d'imprimer 65 codes barres sur une page. Soit pour un même code barre soit pour des codes barre différents.

2019-03-11 11:28 UTC, remytms requested changes
Il y a trop de commit qui ne concernent pas le product_report. Probablement du à un mauvais branchage, ou à des dépendance nécessaire. Mais en tous cas, il faut nettoyer ça et ne garder que les commit nécessaires.

2019-03-11 11:28 UTC, remytms commented on product_report_v10/report/layout.xml
> -  </template>
Ici il ne faudrait pas modifier le code précédent. C'est l'éditeur de texte qui l'a fait tout seul, mais il ne faudrait pas le commiter dans git.

2019-03-11 11:28 UTC, remytms commented on product_report_v10/report/layout.xml
> +
Il y a deux lignes inutiles ici. :)

2019-03-13 09:22 UTC, nicolasj77 commented on product_report_v10/report/layout.xml
> +
Done

2019-03-19 11:02 UTC, merged