[ADD] add module res_users_case_insensitive
houssine78/addons pull request #142
Opened 2019-04-01 14:05 UTC by houssine78

2019-04-01 18:31 UTC, remytms requested changes
I've done my comment. At least change the version number. :)

2019-04-01 18:31 UTC, remytms commented on res_users_case_insensitive/__manifest__.py
> +    "version": "9.0.1.0.0",
Version number should be : 11.0.1.0

2019-04-01 18:31 UTC, remytms commented on res_users_case_insensitive/models/res_users.py
> +        size=64,
I don't see what's the benefit of limiting the size of the login to 64 characters. In odoo 11, this field is not limited. See this definition in the `odoo/addons/base/res/res_users.py` file :

```python
    login = fields.Char(required=True, help="Used to log into the system")
```

2019-04-02 08:25 UTC, remytms commented on res_users_case_insensitive/__manifest__.py
> +    "version": "9.0.1.0.0",
In fact, following [semver](https://semver.org/), it should be : 11.0.1.0.0

2019-04-02 10:27 UTC, houssine78 commented
@remytms done

2019-04-17 13:56 UTC, merged