Ajout du champ du nom de la société, si le contact fait partie du société
houssine78/addons pull request #65
Opened 2018-09-04 09:49 UTC by e-jim

Rapidement testé sur l'instance de test.

2018-09-04 12:36 UTC, houssine78 requested changes

2018-09-04 12:36 UTC, houssine78 commented on resource_activity/reports/activity_registration_report.xml
> +		  <div t-if="o.partner_id.parent_id" t-field="o.partner_id.parent_id"/>
ne manque-t-il pas le .name sur le parent pour avoir t-field="o.partner_id.parent_id.name"?

2018-09-04 12:36 UTC, houssine78 commented on resource_activity/reports/activity_report.xml
> +		<div t-if="o.partner_id.parent_id" t-field="o.partner_id.parent_id"/>
idem

2018-09-05 14:47 UTC, e-jim commented on resource_activity/reports/activity_report.xml
> +		<div t-if="o.partner_id.parent_id" t-field="o.partner_id.parent_id"/>
Ce serait sans doute plus propre, effectivement.
Cela dit, ça semble fonctionner.

Par exemple, le code suivant:

````          

<b>parent_id</b>
<div t-if="o.partner_id.parent_id" t-field="o.partner_id.parent_id"/>
<b>Parent_id.name</b>
<div t-if="o.partner_id.parent_id.name" t-field="o.partner_id.parent_id.name"/>

```

donne le rendu suivant: 

![image](https://user-images.githubusercontent.com/5951377/45099810-7be1bd80-b128-11e8-89c8-77ec7ea6235d.png)

Mais soyons honnêtes, je ne sais pas toujours entièrement ce que je fais... 😬

Je modifie cela tout de suite pour que ce soit plus propre/sémantiquement plus correct. 
Et du coup, j'en profiterai pour ajouter des infos manquantes (certains numéros de tél/mobile).

2018-09-06 14:24 UTC, e-jim commented
@houssine78 Voilà qui est fait, j'ai appliqué ta suggestion.

2018-09-07 10:06 UTC, houssine78 approved these changes

2018-09-07 10:09 UTC, houssine78 requested changes

2018-09-07 10:09 UTC, houssine78 commented on resource_activity/reports/activity_registration_report.xml
> +		  <div t-if="o.partner_id.name" t-field="o.partner_id.name" />
en fait tu as été un peu loin. Le t-if ne doit se faire que sur le o.partner_id.parent_id et que le o.partner_id et c'est sur le t-field que tu affiches le name

2018-09-07 10:09 UTC, houssine78 commented on resource_activity/reports/activity_report.xml
> +		<span t-if="o.partner_id.name" t-field="o.partner_id.name" />
pareil ici

2018-09-07 10:09 UTC, houssine78 commented on resource_activity/reports/activity_report.xml
> +                <span t-if="o.partner_id.mobile">Mob: <span t-field="o.partner_id.mobile" />
pour le téléphone et le gsm c'est ok car on ne veut les afficher que s'ils sont définis

2018-09-10 09:36 UTC, robinkeunen requested changes

2018-09-10 09:36 UTC, robinkeunen commented on resource_activity/reports/activity_report.xml
> +                <span t-if="o.partner_id.mobile">Mob: <span t-field="o.partner_id.mobile" />
Les `span` phone et mobile ne sont pas fermés, si?

2018-09-10 13:56 UTC, robinkeunen commented on resource_activity/reports/activity_report.xml
> +                <span t-if="o.partner_id.mobile">Mob: <span t-field="o.partner_id.mobile" />
Quelque chose comme:
```xml
<div class="row" name="clients-nom">
  <h4>Name:</h4>
  <t t-if="o.partner_id.parent_id"> <span t-field="o.partner_id.parent_id.name"/> <br/> </t>
  <span t-if="o.partner_id.name" t-field="o.partner_id.name" /> <br/>
  <t t-if="o.partner_id.phone">Tel: <span t-field="o.partner_id.phone" /> <br/> </t>
  <t t-if="o.partner_id.mobile">Mob: <span t-field="o.partner_id.mobile" /></t>
</div>
```

2018-09-19 12:53 UTC, closed without merging