Ajout filtres
houssine78/addons pull request #77
Opened 2018-09-20 16:27 UTC by e-jim

Ajout de filtres et adaptation du filtre par défaut
Les filtres d'implantations (Bruxelles et Mons) sont hardcodés parce que:
1. on utilise des "pseudo-implantations" comme stocks (exemple: Bruxelles - Bike Project)
2. Toutes les implantations n'utilisent pas encore l'outil --> limitons le filtre à ce qui est pertinent.

Après, si vous avez une meilleure solution en terme de maintenabilité.

2018-09-26 14:26 UTC, robinkeunen requested changes
Salut Jérémy,

Ces filtres m'ont l'air utiles, sauf:

- `scheduled` et `what's next` qui sont, selon moi, trop proches. Autant n'en garder qu'un.
- les filtres d'emplacement sont spécifiques à votre _use case_, donc je préférerais ne pas l'intégrer dans la code base. Tu peux les crééer par l'interface et les rendre displonibles à tout le monde.

Merci :-)

2018-09-26 14:26 UTC, robinkeunen commented on resource_activity/views/resource_activity_views.xml
>                      	domain="[('date_start','&gt;=', time.strftime('%Y-%m-%d 00:00:00')), ('date_end','&gt;=', time.strftime('%Y-%m-%d 00:00:00'))]"/>
```xml
domain="[('date_start','&gt;=', time.strftime('%Y-%m-%d 00:00:00'))]"/>
```
Would be enough here.

2018-09-26 14:26 UTC, robinkeunen commented on resource_activity/views/resource_activity_views.xml
>                      <filter name="ongoing" string="Ongoing"
It would be more readable in this form:

```xml
                    <filter name="ongoing" string="Ongoing"
                    	domain="[('date_start', '<=', time.strftime('%Y-%m-%d %H:%M:%S')),
                    	         ('date_end', '>=', time.strftime('%Y-%m-%d %H:%M:%S'))]"/>
```

2018-09-26 23:37 UTC, e-jim commented on resource_activity/views/resource_activity_views.xml
>                      <filter name="ongoing" string="Ongoing"
Merci pour tes retours. 
Même si ils portent essentiellement sur des filtres que vous avez écrits et pas sur mes commits ;)

J'ai supprimé le filtre scheduled et les filtres hardcodés portant sur les implantations, que j'ai mis en favoris.

2018-09-27 08:36 UTC, robinkeunen commented on resource_activity/views/resource_activity_views.xml
>                      <filter name="ongoing" string="Ongoing"
oups :stuck_out_tongue:

2018-09-27 08:37 UTC, robinkeunen approved these changes
Top, je merge!

merci :-)

2018-09-27 08:38 UTC, merged